"use client";

import { ArrowLeft, Printer } from "lucide-react";
import { AppShell, Logo, PageLoader } from "@/components/shell";
import { Button, LinkButton } from "@/components/ui";
import { d, money } from "@/lib/format";
import { useApi } from "@/lib/useApi";

type Cert = {
  employee: { name: string; title: string; department: string; grade: string; joined_on: string; email: string };
  company: { name: string };
  issued_on: string;
  monthly: { basic: number; house_rent: number; utilities: number; gross: number };
  annual_gross: number;
};

export default function CertificatePage() {
  return (
    <AppShell>
      <Certificate />
    </AppShell>
  );
}

function Certificate() {
  const { data } = useApi<Cert>("/me/certificate");
  if (!data) return <PageLoader />;
  const e = data.employee;
  return (
    <div className="mx-auto max-w-3xl">
      <div className="no-print mb-4 flex justify-between">
        <LinkButton href="/app/payslips" variant="soft" size="sm">
          <ArrowLeft size={15} /> Payslips
        </LinkButton>
        <Button size="sm" onClick={() => window.print()}>
          <Printer size={15} /> Print or save as PDF
        </Button>
      </div>
      <article className="card p-10 sm:p-14">
        <div className="flex items-center justify-between">
          <Logo />
          <p className="text-xs text-muted">Issued {d(data.issued_on, { day: "numeric", month: "long", year: "numeric" })}</p>
        </div>
        <h1 className="mt-10 text-center text-2xl font-bold tracking-tight">Salary certificate</h1>
        <p className="mt-8 text-[15px] leading-relaxed text-ink-2">
          This is to certify that <span className="font-semibold text-ink">{e.name}</span> has been employed with{" "}
          <span className="font-semibold text-ink">{data.company.name}</span> since {d(e.joined_on, { day: "numeric", month: "long", year: "numeric" })} as{" "}
          <span className="font-semibold text-ink">{e.title}</span> ({e.department}, grade {e.grade}). Their current monthly salary is as follows:
        </p>
        <table className="mt-6 w-full text-[14px]">
          <tbody className="divide-y divide-line">
            {[
              ["Basic salary", data.monthly.basic],
              ["House rent allowance", data.monthly.house_rent],
              ["Utilities allowance", data.monthly.utilities],
            ].map(([k, v]) => (
              <tr key={k as string}>
                <td className="py-2.5 text-ink-2">{k}</td>
                <td className="num py-2.5 text-right">{money(v as number)}</td>
              </tr>
            ))}
            <tr className="font-semibold">
              <td className="py-2.5">Gross monthly salary</td>
              <td className="num py-2.5 text-right">{money(data.monthly.gross)}</td>
            </tr>
            <tr className="font-semibold">
              <td className="py-2.5">Gross annual salary</td>
              <td className="num py-2.5 text-right">{money(data.annual_gross)}</td>
            </tr>
          </tbody>
        </table>
        <p className="mt-8 text-[13px] text-muted">This certificate is issued at the employee&apos;s request. Generated by {data.company.name} payroll records.</p>
        <p className="mt-10 rounded-2xl bg-warn-soft px-4 py-3 text-xs text-warn">Demo company and fictional employee: not a real document.</p>
      </article>
    </div>
  );
}
